# **Seminário de Teoria Espectral das Matrizes**

# Método de Potência e Computação de Autovalores e Autovetores

### Introdução
No presente trabalho, iremos apresentar sobre o Método de Potência e Computação de Pares Próprios. O Método de Potência, também conhecido como iteração de Von Mises, tem o objetivo de aproximar autovalores extremos da matriz, ou seja, autovalores de menor e maior módulo com seus autovetores associados. Sabemos calcular o autovalor de uma matriz através do polinômio característico, mas encontrar o determinante computacionalmente da seguinte forma pode ser ineficiente e dispendioso.

Atráves dos métodos de iteração e definições  da Aĺgebra Linear com apenas um algoritmo simples, obtemos resultados muito importante para aplicações em diversas áreas da ciência como geossísmica, máquinas e vibrações estruturais, mecânica quântica etc.

Dada uma matriz A, o algoritmo irá produzir um autovalor $\mathbf{\lambda}$ e um vetor não-nulo, tal que $\mathbf{Av=\lambda v}$. A operação não computa decomposição matricial e podemos usar quando A for uma grande matriz esparsa. Com isso, ele irá convergir a apenas um autovalor $\mathbf{\lambda}$.

---



### Construção do algoritmo

Seja $\mathbf{A}$ uma matriz $n \times n$ com $n$ autovetores $\mathbf{V}$ linearmente indepentes, com seus autovalores $\lambda_1, \lambda_2, ..., \lambda_n$, e  que $\lambda_1$ seja o maior autovalor em módulo.

Seja $\mathbf{x}$ um vetor qualquer em $\mathbb{R}^n$. Como o conjunto de autovetores $\mathbf{V} = \{\mathbf{v}^{(1)},\mathbf{v}^{(2)},..., \mathbf{v}^{(n)} \}$ é L.I, podemos escrever:

$$
\mathbf{x}= \sum^n_{j=1}\beta_j\mathbf{v}^{(n)}
$$

Multiplicando por $\mathbf{A^k}$ em ambos os lados, temos que:

$$
\mathbf{A^k}\mathbf{x}= \sum^n_{j=1}\beta_j\lambda^k_j\mathbf{v}^{(j)}
$$

Fatorando o lado direito da equação por $\lambda^k_1$, obtemos:

$$
\mathbf{A^k}\mathbf{x}= \lambda^k_1\sum^n_{j=1}\beta_j\left(\frac{\lambda_j}{\lambda_1}\right)^k\mathbf{v}^{(j)}
$$

Como $|\lambda_1|>|\lambda_j|$, para qualquer $j \neq 1$, então $\lim_{k \to \infty}\left(\frac{\lambda_j}{\lambda_1}\right)^k = 0$ e:

$$
\lim_{k \to \infty}\mathbf{A^k}\mathbf{x}= \lim_{k \to \infty} \lambda^k_1\beta_1\mathbf{v}^{(1)}
$$

O Método da Potência Inversa é uma alteração do método original, convergindo mais rápido. É utilizado para determinar o autovalor de $A$ qeu esteja mais próximo de um número $q$ (Quociente de Rayleigh) especificado. Este método converge da seguinte forma $(A-qI)^-1$. Sendo $q$ da seguinte forma:

$$ q = \frac{x^tAx}{x^tx} $$

Se $q$ estiver mais próximo de um autovalor, a convegência será bastante rápida.



In [ ]:
import numpy as np

# Método da Potência Inversa
# Utilizado para determinar o autovalor de A que esteja mais próximo de um autovetor especificado
# Quociente de Rayleigh, calcular o raio espectral da matriz

def met_potencia_inversa(A,x,n,e):    
    xn = x
    q_prev = 0

    # Para cada iteração, o vetor xn é multiplicado pela matriz A e normalizado 
    for i in range(n):
        # Se x for um autovetor de A correspondente ao autovalor lambda, então Ax = lambda*x        
        autovalor = np.dot(xn.transpose(),np.dot(A,xn))/np.dot(xn.transpose(),xn) # x^t * A * x / x^t * x
      
        xn = np.dot(A,xn)
      
        xn = xn/max(xn)
        
        if(np.abs(autovalor-q_prev) < e and i != 0):
            print(('Iteração: ') + str(i))
            print(('Maior autovalor: ')+str(autovalor.max()))
            return (autovalor,xn)
        q_prev = autovalor


#M = np.array([[4,2,3],[2,7,6],[3,6,4]])
#M = np.array([[-4,14,0],[-5,13,0],[-1,0,2]])
M = np.array([[4,-1,1], [-1,3,-2],[1,-2,3]])
x_init = np.array([[1],[1],[1]])
met_potencia_inversa(M,x_init,15,0.01)

Iteração: 6
Maior autovalor: 5.998535857385613


(array([[5.99853586]]), array([[ 1.        ],
        [-0.97691253],
        [ 0.97693363]]))

O Método da Potência Original, faz a convergência a partir de $Ax = y$, pegando o maior elemento de  $y$ dividindo todo o vetor por ele .

In [ ]:
# Método da Potência 'Normal'
def met_potencia_normal(A,x,n,e):
  k = 1

  x2 = x / max(x)
  antigo = 0
  for k in range(n):
    y = np.dot(A,x)
    u = max(y)
    
    if u == 0:
      print('Autovetor\n', x)
      print('A tem autovalor 0, escolha um novo vetor x e reinicie')
      break
    
    x = y/max(y)
    
    if(np.abs(u-antigo) < e and k != 0):
      print(('Iteração: ') + str(k))
      return (u,x)
      break
    
    antigo = u
#M2 = np.array([[-4,14,0],[-5,13,0],[-1,0,2]])
M2 = np.array([[4,-1,1], [-1,3,-2],[1,-2,3]])
met_potencia_normal(M,x_init,15,0.001)


Iteração: 13


(array([5.99926776]), array([[ 1.        ],
        [-0.99981692],
        [ 0.99981692]]))

As técnicas de deflação envolvem a formação de uma nova matriz $B$ cujo autovalores sejam os mesmos de $A$, exceto o autovalor dominante em A que é substituído por 0. Calculamos $B$ como:

$$ B = A - \lambda v^1 x^t $$



In [ ]:
# Deflação de Wielandt

M2 = np.array([[4,-1,1], [-1,3,-2],[1,-2,3]])
x_init = np.array([[1],[1],[1]])
autovalor,autovetor = met_potencia_normal(M2,x_init,15,0.01)

for i in range(3):
  x = (1 / (autovalor*autovetor[i]))* M2[0,:]
  vx = x*autovetor
  B = M2 - (autovalor*vx)

B_2 = np.delete(B,(0),axis=0)
B_3 = np.delete(B_2,0,axis = 1)

x_init2 = np.array([[1],[0]])
autovalorB, autovetorB = met_potencia_normal(B_3,x_init2,15,0.001)

autovetorB = np.concatenate((np.zeros(shape=(1,1)),autovetorB))
v_2 =  (autovalorB - autovalor)*autovetorB + autovalor*(np.dot(x, autovetorB))*autovetor
print(autovalorB)
print(v_2)



Iteração: 10
Iteração: 8
[2.99969523]
[[-2.00282933]
 [-0.99455847]
 [ 0.99425413]]


[[-2.00282933]
 [-0.99455847]
 [ 0.99425413]]
